MODEL:
  BACKBONE:
    NAME: bninception

SOLVER:
  MAX_ITERS: 3000
  STEPS: [1200, 2400]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.000027
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005
  
DATA:
  TRAIN_IMG_SOURCE: /data/songkun/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: /data/songkun/CUB_200_2011/test.txt
  TRAIN_BATCHSIZE: 70
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 8
  NUM_INSTANCES: 8

VALIDATION:
  VERBOSE: 200